
<! DOCTYPE HTML>
<html>
<head>
     <meta charset="UTF-8"/>
     <title>FA Cup 2007/08</title>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

 </head>
<body>

<table class="table">
 <thead>
  <tr>
   <th colspan="3" style="text-align: center;">KPI</th>
   <th>Jan</th>
   <th>Feb</th>
   <th>Mar</th>
   <th>Apr</th>
   <th>May</th>
   <th>Jun</th>
   <th>Jul</th>
   <th>Aug</th>
   <th>Sep</th>
   <th>Oct</th>
   <th>Nov</th>
   <th>Dec</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td rowspan="6" style="text-align: center; vertical-align: middle">Market</td>
   <td rowspan="3" style="text-align: center; vertical-align: middle">FFR</td>
   <td>'17</td>
   <td>2,62</td>
   <td>2,31</td>
   <td>2,18</td>
   <td>2,29</td>
   <td>2,48</td>
   <td>2,42</td>
   <td>2,23</td>
   <td>2,12</td>
   <td>2,07</td>
   <td>1,97</td>
   <td>1,80</td>
   <td>1,72</td>
  </tr>
  <tr>
   <td>'18</td>
   <td>1,67</td>
   <td>1,56</td>
   <td>1,50</td>
   <td>1,52</td>
   <td>1,48</td>
   <td>1,47</td>
   <td>1,48</td>
   <td>1,44</td>
   <td>1,44</td>
   <td>1,39</td>
   <td></td>
   <td></td>
  </tr>
  <tr>
   <td>Improvement</td>
   <td>Taxa <img src="uparrow.svg" alt="Logo" /></td>
  </tr>
  <tr>
   <td rowspan="3" style="text-align: center; vertical-align: middle">FCR</td>
   <td>'17</td>
   <td>1,01</td>
   <td>1,22</td>
   <td>1,45</td>
   <td>1,56</td>
   <td>1,60</td>
   <td>1,57</td>
   <td>1,49</td>
   <td>1,40</td>
   <td>1,28</td>
   <td>1,14</td>
   <td>1,06</td>
   <td>1,04</td>
  </tr>
  <tr>
   <td>'18</td>
   <td>0,76</td>
   <td>0,87</td>
   <td>0,95</td>
   <td>1,21</td>
   <td>1,33</td>
   <td>1,24</td>
   <td>1,18</td>
   <td>1,13</td>
   <td>1,09</td>
   <td>1,05</td>
   <td></td>
   <td></td>
  </tr>
  <tr>
   <td>Improvement</td>
   <td>Rate</td>
  </tr>
  <tr>
   <td rowspan="9" style="text-align: center; vertical-align: middle">Saengsang</td>
   <td rowspan="3" style="text-align: center; vertical-align: middle">PRR</td>
   <td>'17</td>
   <td>0</td>
   <td>10</td>
   <td>91</td>
   <td>140</td>
   <td>259</td>
   <td>295</td>
   <td>299</td>
   <td>379</td>
   <td>395</td>
   <td>453</td>
   <td>494</td>
   <td>531</td>
  </tr>
  <tr>
   <td>'18</td>
   <td>728</td>
   <td>712</td>
   <td>636</td>
   <td>579</td>
   <td>567</td>
   <td>564</td>
   <td>501</td>
   <td>486</td>
   <td>479</td>
   <td>482</td>
   <td></td>
   <td></td>
  </tr>
  <tr>
      <td>Improvement</td>
      <td>Rate</td>
  </tr>
  <td rowspan="3" style="text-align: center; vertical-align: middle">TLDR</td>
   <td>'17</td>
   <td>3648</td>
   <td>3597</td>
   <td>3322</td>
   <td>140</td>
   <td>259</td>
   <td>295</td>
   <td>299</td>
   <td>379</td>
   <td>395</td>
   <td>453</td>
   <td>494</td>
   <td>531</td>
  </tr>
  <tr>
   <td>'18</td>
   <td>2210</td>
   <td>2051</td>
   <td>2322</td>
   <td>2277</td>
   <td>567</td>
   <td>564</td>
   <td>501</td>
   <td>486</td>
   <td>479</td>
   <td>482</td>
   <td></td>
   <td></td>
  </tr>
  <tr>
      <td>Improvement</td>
      <td>Rate</td>
  </tr>
  <td rowspan="3" style="text-align: center; vertical-align: middle">IFRR</td>
   <td>'17</td>
   <td>0,56</td>
   <td>0,0</td>
   <td>0,31</td>
   <td>0,24</td>
   <td>2,87</td>
   <td>0,34</td>
   <td>2,72</td>
   <td>0,22</td>
   <td>0,14</td>
   <td>0,85</td>
   <td>0,00</td>
   <td>0,22</td>
  </tr>
  <tr>
   <td>'18</td>
   <td>0,56</td>
   <td>0,0</td>
   <td>0,31</td>
   <td>0,24</td>
   <td>2,87</td>
   <td>0,34</td>
   <td>2,72</td>
   <td>0,22</td>
   <td>0,14</td>
   <td>0,85</td>
   <td></td>
   <td></td>
  </tr>
  <tr>
      <td>Improvement</td>
      <td>Rate</td>
  </tr>
  <tr>
      <td rowspan="3" style="text-align: center; vertical-align: middle">Issue</td>
      <td style="text-align: center";>Primeira linha</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td></td>
      <td></td>
  </tr>
  <tr>
      <td style="text-align: center";>Segunda linha</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td></td>
      <td></td>
  </tr>
  <tr>
      <td style="text-align: center";>Terceira linha</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td></td>
      <td></td>
  </tr>
 </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>